### ISSUE TITLE
Firebase reporting Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by dzboot02** [kristiyanP/colorpicker#23]
```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4659)
       at android.view.ViewGroup.addView(ViewGroup.java:4495)
       at android.view.ViewGroup.addView(ViewGroup.java:4436)
       at android.view.ViewGroup.addView(ViewGroup.java:4409)
       at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:460)
       at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:99)
       at petrov.kristiyan.colorpicker.CustomDialog.onCreate(CustomDialog.java:20)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:733)
       at android.app.Dialog.show(Dialog.java:469)
       at petrov.kristiyan.colorpicker.ColorPicker.show(ColorPicker.java:259)
       at com.warrina.sudan.activities.TextStatusActivity.lambda$onCreate$0(TextStatusActivity.java:90)
       at com.warrina.sudan.activities.TextStatusActivity.lambda$XnQftIRXbnjIHQavQwiQSa4skdo(TextStatusActivity.java)
       at com.warrina.sudan.activities.-$$Lambda$TextStatusActivity$XnQftIRXbnjIHQavQwiQSa4skdo.onClick(lambda)
       at android.view.View.performClick(View.java:5721)
       at android.view.View$PerformClick.run(View.java:22620)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

This happens randomly

**Comment by kristiyanP** [comment]
Update to 1.1.10 and let me know if it continues to happen

**Comment by dzboot02** [comment]
With 1.1.10 I can't even build my app, I am getting this:

```
> Task :app:processDebugManifest FAILED
D:\Fahed\LocalProjects\Android\Warrina\app\src\main\AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-504:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:19:5-504:19 to override.
```

**Comment by kristiyanP** [comment]
That is probably because you are using support compat 28.0.0. Google has released androidx which is equivalent to the support 28.0.0, but has a lot less of useless code inside. You should consider to update to androidx. The lib has migrated to androidx since v1.1.9

**Comment by raghavtilak** [comment]
I am facing the same issue. And I am using **'petrov.kristiyan:colorpicker-library:1.1.10'**
